<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Local extends \AppBundle\Entity\Local implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'categoria', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'nivel', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'local', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'horario', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'horario2', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'logo', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'imagen', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'web', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'nit', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'arrendatario', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'x', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'y', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'fecha_modificacion', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'fecha_creacion');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'categoria', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'nombre', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'nivel', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'local', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'telefono', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'horario', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'horario2', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'logo', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'imagen', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'web', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'nit', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'arrendatario', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'x', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'y', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'fecha_modificacion', '' . "\0" . 'AppBundle\\Entity\\Local' . "\0" . 'fecha_creacion');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Local $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoria(\AppBundle\Entity\Categoria $categoria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoria', array($categoria));

        return parent::setCategoria($categoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoria', array());

        return parent::getCategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNivel($nivel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNivel', array($nivel));

        return parent::setNivel($nivel);
    }

    /**
     * {@inheritDoc}
     */
    public function getNivel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNivel', array());

        return parent::getNivel();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocal($local)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocal', array($local));

        return parent::setLocal($local);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocal', array());

        return parent::getLocal();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', array($telefono));

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', array());

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorario($horario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorario', array($horario));

        return parent::setHorario($horario);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorario', array());

        return parent::getHorario();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorario2($horario2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorario2', array($horario2));

        return parent::setHorario2($horario2);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorario2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorario2', array());

        return parent::getHorario2();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo($logo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo', array($logo));

        return parent::setLogo($logo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', array());

        return parent::getLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeb($web)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeb', array($web));

        return parent::setWeb($web);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeb', array());

        return parent::getWeb();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagen($imagen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagen', array($imagen));

        return parent::setImagen($imagen);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagen', array());

        return parent::getImagen();
    }

    /**
     * {@inheritDoc}
     */
    public function setNit($nit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNit', array($nit));

        return parent::setNit($nit);
    }

    /**
     * {@inheritDoc}
     */
    public function getNit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNit', array());

        return parent::getNit();
    }

    /**
     * {@inheritDoc}
     */
    public function setArrendatario($arrendatario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArrendatario', array($arrendatario));

        return parent::setArrendatario($arrendatario);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrendatario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrendatario', array());

        return parent::getArrendatario();
    }

    /**
     * {@inheritDoc}
     */
    public function setX($x)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setX', array($x));

        return parent::setX($x);
    }

    /**
     * {@inheritDoc}
     */
    public function getX()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getX', array());

        return parent::getX();
    }

    /**
     * {@inheritDoc}
     */
    public function setY($y)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setY', array($y));

        return parent::setY($y);
    }

    /**
     * {@inheritDoc}
     */
    public function getY()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getY', array());

        return parent::getY();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaModificacion($fechaModificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaModificacion', array($fechaModificacion));

        return parent::setFechaModificacion($fechaModificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaModificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaModificacion', array());

        return parent::getFechaModificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', array($fechaCreacion));

        return parent::setFechaCreacion($fechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', array());

        return parent::getFechaCreacion();
    }

}
